// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhIMHiXU9b5NpySdZEGeZFH3LhEI5FiPI',
    appId: '1:58869684834:web:992eb7fec2f7eec40c0f3b',
    messagingSenderId: '58869684834',
    projectId: 'vibe-verse-8d5c6',
    authDomain: 'vibe-verse-8d5c6.firebaseapp.com',
    storageBucket: 'vibe-verse-8d5c6.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf6-JuaNI3aTRq52ygacV5Loug-C39cts',
    appId: '1:58869684834:ios:c849056dd97608e30c0f3b',
    messagingSenderId: '58869684834',
    projectId: 'vibe-verse-8d5c6',
    storageBucket: 'vibe-verse-8d5c6.appspot.com',
    iosBundleId: 'com.example.vibeVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhIMHiXU9b5NpySdZEGeZFH3LhEI5FiPI',
    appId: '1:58869684834:web:05c48eb488798d970c0f3b',
    messagingSenderId: '58869684834',
    projectId: 'vibe-verse-8d5c6',
    authDomain: 'vibe-verse-8d5c6.firebaseapp.com',
    storageBucket: 'vibe-verse-8d5c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6-JuaNI3aTRq52ygacV5Loug-C39cts',
    appId: '1:58869684834:ios:c849056dd97608e30c0f3b',
    messagingSenderId: '58869684834',
    projectId: 'vibe-verse-8d5c6',
    storageBucket: 'vibe-verse-8d5c6.appspot.com',
    iosBundleId: 'com.example.vibeVerse',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Q5WeepVd5_13JqSrXLA9SHm0D5G0AAc',
    appId: '1:58869684834:android:2784d14605a898bf0c0f3b',
    messagingSenderId: '58869684834',
    projectId: 'vibe-verse-8d5c6',
    storageBucket: 'vibe-verse-8d5c6.appspot.com',
  );

}